version: '3.8'
networks:
  fr_api:
    driver: bridge

services:
  ai_service:
    image: $IMAGE_NAME/ai_service:$VERSION
    container_name: ai_service.$DOMAIN

    ports: 
      - 7001:7001

    command: bash -c "python main.py"
   
    networks:
      - fr_api
